export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  BROKER = 'BROKER',
  VERIFIED_BROKER = 'VERIFIED_BROKER',
  PREMIUM_BROKER = 'PREMIUM_BROKER',
  ENTERPRISE_BROKER = 'ENTERPRISE_BROKER',
}
